<a href="https://colab.research.google.com/github/NguyenDucHuyCNTT31/THToanCaoCap/blob/main/TH_Ch%C6%B0%C6%A1ng5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài TH1

In [29]:
x =3 
print(x)


3


In [32]:
import math
x= math.sqrt(x+1)
print(x)

2.0


Bài TH2 

In [34]:
 import math
 x=10
 lap = 1
 while (x!= math.sqrt(x+1)):
   x = math.sqrt(x+1)
   lap = lap + 1
print(lap)
print(x)


34
1.618033988749895


Bài Th3

In [9]:
import sympy as sp
from sympy import Symbol
x= Symbol('x')
sp.solve( x- sp.sqrt(x+1),x)



[1/2 + sqrt(5)/2]

Bài TH 4

In [16]:
import numpy as np
v1 = np .array([1,2,3])
v2= np. array([2,1,0])
v3 = v1 + v2
v3


array([3, 3, 3])

In [17]:
3*v1 +2*v2

array([7, 8, 9])

In [20]:
v4 =  np.hstack([v1,v2])
v4

array([1, 2, 3, 2, 1, 0])

In [21]:
v5 = np.dot(v1,v2)
v5

4

In [23]:
angles= np.linspace(0, np.pi/2.5)
angles

array([0.        , 0.02564565, 0.05129131, 0.07693696, 0.10258262,
       0.12822827, 0.15387393, 0.17951958, 0.20516523, 0.23081089,
       0.25645654, 0.2821022 , 0.30774785, 0.33339351, 0.35903916,
       0.38468481, 0.41033047, 0.43597612, 0.46162178, 0.48726743,
       0.51291309, 0.53855874, 0.56420439, 0.58985005, 0.6154957 ,
       0.64114136, 0.66678701, 0.69243267, 0.71807832, 0.74372398,
       0.76936963, 0.79501528, 0.82066094, 0.84630659, 0.87195225,
       0.8975979 , 0.92324356, 0.94888921, 0.97453486, 1.00018052,
       1.02582617, 1.05147183, 1.07711748, 1.10276314, 1.12840879,
       1.15405444, 1.1797001 , 1.20534575, 1.23099141, 1.25663706])

In [38]:

from sympy import sin as sysin
angles = np . linspace(0, np.pi/2.5)
sinangle = np.zeros(5)
len(angles)
for i in range(len(angles)):
  sinangle[i]= sysin(angles[i])




IndexError: ignored